language: c
matrix:
        allow_failures:
                - os: osx
        include:
                # Default build
                - os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - xsltproc
                                          - docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # GTK2 build
                - os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview2.0-dev
                                          - gettext
                                          - xsltproc
                                          - docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall --with-gtk2 && make && make install

                # Default build on OS X
                - os: osx
                  before_install:
                          - brew install pkg-config
                          - brew install vala
                          - brew install glib
                          - brew install cairo
                          - brew install libffi
                          - brew install gdbm
                          - brew install openssl
                          - brew install readline
                          - brew install sqlite
                          - brew install python@2
                          - brew install gobject-introspection
                          - brew install intltool
                          - brew install gtksourceview3
                          - brew install libxslt
                          - brew install docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # Default build on OS X 10.13 (High Sierra)
                - os: osx
                  osx_image: xcode9.3
                  before_install:
                          - brew install pkg-config
                          - brew install vala
                          - brew install glib
                          - brew install cairo
                          - brew install libffi
                          - brew install gdbm
                          - brew install openssl
                          - brew install readline
                          - brew install sqlite
                          - brew install python@2
                          - brew install gobject-introspection
                          - brew install intltool
                          - brew install gtksourceview3
                          - brew install libxslt
                          - brew install docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # GTK2 build on OS X
                - os: osx
                  before_install:
                          - brew install pkg-config
                          - brew install gtksourceview
                          - brew install libxslt
                          - brew install docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall --with-gtk2 && make && make install

