language: c
matrix:
        allow_failures:
                - os: linux
                  dist: xenial
        include:
                - name: "Linux autotools build"
                  os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - discount
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install && make dist && tar -tzvf gnusim8085*.tar.*

                - name: "Linux meson build"
                  os: linux
                  dist: xenial
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - discount
                                          - meson
                  script: rm -rf builddir && meson --prefix=`pwd`/mesoninstall builddir && cd builddir && ninja dist && cd ..

                - name: "OS X autotools build"
                  os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew bundle
                          - brew link --force gettext
                  script:
                          - ./autogen.sh
                          - ./configure --prefix=`pwd`/tempinstall
                          - make install
                          - otool -L tempinstall/bin/gnusim8085
                          - make dist
                          - tar -tzvf gnusim8085*.tar.*

                - name: "OS X meson build"
                  os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew install gtk+3
                          - brew install gtksourceview3
                          - brew install gettext
                          - brew install discount
                          - brew install dylibbundler
                          - brew link --force gettext
                          - brew install meson
                  script:
                          - rm -rf builddir
                          - meson --prefix=/tmp/GNUSim8085.app --bindir=Contents/MacOS --datadir=Contents/Resources --localedir=Contents/Resources/locale --mandir=Contents/SharedSupport -Dbuild-osx-app=true builddir
                          - cd builddir && ninja install && ninja dist && cd ..
                          - otool -L /tmp/GNUSim8085.app/Contents/MacOS/gnusim8085
                          - ls -R /tmp/GNUSim8085.app

