language: c
matrix:
        allow_failures:
                - os: osx
        include:
                # Default build
                - os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - xsltproc
                                          - docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # GTK2 build
                - os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview2.0-dev
                                          - gettext
                                          - xsltproc
                                          - docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall --with-gtk2 && make && make install

                # Default build on OS X
                - os: osx
                  before_install:
                          - brew list
                          - brew install pkg-config
                          - brew install gtksourceview3
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # Default build using meson on OS X 10.12 (Sierra)
                - os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew uninstall python
                          - brew install pkg-config
                          - brew install gtksourceview3
                          - brew install meson
                  script: rm -rf builddir && meson setup . builddir && meson introspect builddir && cd builddir && ninja

                # GTK2 build on OS X
                - os: osx
                  before_install:
                          - brew list
                          - brew uninstall mercurial
                          - brew uninstall python
                          - brew install gtksourceview
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall --with-gtk2 && make && make install

