language: c
matrix:
        allow_failures:
                - os: osx
        include:
                # Default build
                - os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - xsltproc
                                          - docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # GTK2 build
                - os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview2.0-dev
                                          - gettext
                                          - xsltproc
                                          - docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall --with-gtk2 && make && make install

                # Default build on OS X
                - os: osx
                  before_install:
                          - brew list
                          - brew install pkg-config
                          - brew install gtksourceview3
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # Default build on OS X 10.13 (High Sierra)
                - os: osx
                  osx_image: xcode9.3
                  before_install:
                          - brew list
                          - brew install pkg-config
                          - brew install gtksourceview3
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # GTK2 build on OS X
                - os: osx
                  before_install:
                          - brew list
                          - brew uninstall python
                          - brew install glib
                          - brew deps --tree --annotate --include-requirements --include-optional gsettings-desktop-schemas
                          - brew install --ignore-dependencies gsettings-desktop-schemas
                          - brew install pkg-config
                          - brew uses --recursive python@2
                          - brew deps --tree --annotate --include-requirements --include-optional gtk+
                          - brew install gtk+
                          - brew install gtk-mac-integration
                          - brew deps --tree --annotate --include-requirements --include-optional gtksourceview
                          - brew install --ignore-dependencies gtksourceview
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall --with-gtk2 && make && make install

