language: c
matrix:
        allow_failures:
                - os: osx
        include:
                - name: "Linux autotools build"
                  os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - discount
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install && make dist && tar -tzvf gnusim8085*.tar.*

                - name: "OS X autotools build"
                  os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew uninstall python
                          - brew bundle
                          - brew link --force gettext
                  script:
                          - ./autogen.sh
                          - ./configure --prefix=`pwd`/tempinstall
                          - make install
                          - make dist
                          - tar -tzvf gnusim8085*.tar.*

                - name: "OS X meson build"
                  os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew uninstall python
                          - brew install gtk+3
                          - brew install gtksourceview3
                          - brew install gettext
                          - brew install discount
                          - brew link --force gettext
                          - brew install meson
                  script:
                          - rm -rf builddir
                          - meson --prefix=`pwd`/mesoninstall builddir
                          - cd builddir && ninja install && ninja dist && cd ..

