language: c
matrix:
        allow_failures:
                - os: osx
        include:
                # Default build
                - os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - xsltproc
                                          - docbook-xsl
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # Default build on OS X
                - os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew uninstall python
                          - brew bundle
                          - brew link --force gettext
                  script:
                          - ./autogen.sh
                          - ./configure --prefix=`pwd`/tempinstall --with-xslpath=/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml/docbook.xsl
                          - make install

                # Default build using meson on OS X 10.12 (Sierra)
                - os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew uninstall python
                          - brew install gtksourceview3
                          - brew install gettext
                          - brew link --force gettext
                          - brew install libxslt
                          - brew install docbook-xsl
                          - brew list docbook-xsl
                          - brew install meson
                  script:
                          - rm -rf builddir
                          - meson --prefix=`pwd`/mesoninstall -Dwith-xslpath=/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl/xhtml/docbook.xsl builddir
                          - cd builddir && ninja install && cd ..

