language: c
matrix:
        allow_failures:
                - os: osx
        include:
                # Default build
                - os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - discount
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install

                # Default build on OS X
                - os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew uninstall python
                          - brew bundle
                          - brew link --force gettext
                  script:
                          - ./autogen.sh
                          - ./configure --prefix=`pwd`/tempinstall
                          - make install

                # Default build using meson on OS X 10.12 (Sierra)
                - os: osx
                  before_install:
                          - brew list
                          - brew uninstall --force mercurial
                          - brew uninstall python
                          - brew bundle
                          - brew link --force gettext
                          - brew install meson
                  script:
                          - rm -rf builddir
                          - meson --prefix=`pwd`/mesoninstall builddir
                          - cd builddir && ninja install && cd ..

